definitions:
  model.RequestCreateComplain:
    properties:
      createDateAt:
        type: integer
      exhibitionID:
        type: string
      message:
        type: string
      status:
        $ref: '#/definitions/model.StatusEnum'
      user:
        $ref: '#/definitions/model.User'
    required:
    - exhibitionID
    - message
    type: object
  model.StatusEnum:
    enum:
    - approved
    - rejected
    - pending
    type: string
    x-enum-varnames:
    - Approved
    - Rejected
    - Pending
  model.User:
    properties:
      firstname:
        type: string
      id:
        type: string
      lastname:
        type: string
      profile:
        type: string
    type: object
info:
  contact: {}
  description: Complain Service สำหรับขอจัดการเกี่ยวกับ Workshop Manager ทั้งการสร้าง
    แก้ไข ลบ Workshop Manager
  title: Complain Service API
  version: v0
paths:
  /api/complains:
    get:
      consumes:
      - application/json
      description: GetAllComplains
      operationId: GetAllComplains
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: GetAllComplains
      tags:
      - Complains
    post:
      consumes:
      - application/json
      description: Create a new complain
      operationId: CreateComplain
      parameters:
      - description: Complain data to create
        in: body
        name: requestExhibition
        required: true
        schema:
          $ref: '#/definitions/model.RequestCreateComplain'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Create a new complain
      tags:
      - complain
schemes:
- http
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
